import React, { useState } from 'react';
import { Download, Sliders, HardDrive, Sparkles, FileText, FileAudio, Check, Layers, Cpu } from 'lucide-react';

export interface EQMatrixItem {
  freq: number;
  gain: number;
  q?: number;
}

interface CalibrationExporterProps {
  eqMatrix: EQMatrixItem[];
  profileName?: string;
  targetDevice?: string;
}

export const CalibrationExporter: React.FC<CalibrationExporterProps> = ({
  eqMatrix,
  profileName = 'Studio Monitors Calibration',
  targetDevice = 'Nearfield Studio Monitors',
}) => {
  const [downloadSuccess, setDownloadSuccess] = useState<string | null>(null);
  const [isGeneratingWav, setIsGeneratingWav] = useState<boolean>(false);

  const safeFileName = profileName.toLowerCase().replace(/\s+/g, '_').replace(/[^a-zA-Z0-9_-]/g, '');

  const triggerDownload = (content: string | Blob, fileName: string) => {
    const url = typeof content === 'string'
      ? URL.createObjectURL(new Blob([content], { type: 'text/plain;charset=utf-8' }))
      : URL.createObjectURL(content);

    const link = document.createElement('a');
    link.href = url;
    link.download = fileName;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);

    setDownloadSuccess(`Successfully exported ${fileName}`);
    setTimeout(() => setDownloadSuccess(null), 4000);
  };

  // 1. Equalizer APO (.txt) Export
  const exportEqualizerAPO = () => {
    let text = `# Equalizer APO Configuration File\n`;
    text += `# Profile: ${profileName}\n`;
    text += `# Device: ${targetDevice}\n`;
    text += `# Generated by Resonant Pulse Audio Suite\n`;
    text += `Preamp: 0 dB\n\n`;

    eqMatrix.forEach((item, index) => {
      const q = item.q || 1.414;
      const gainStr = item.gain >= 0 ? `+${item.gain.toFixed(2)}` : `${item.gain.toFixed(2)}`;
      text += `Filter ${index + 1}: ON PK Fc ${item.freq} Hz Gain ${gainStr} dB Q ${q.toFixed(2)}\n`;
    });

    triggerDownload(text, `${safeFileName}_equalizer_apo.txt`);
  };

  // 2. MiniDSP Configuration Export (.xml / .txt)
  const exportMiniDSP = () => {
    let text = `# MiniDSP PEQ Biquad Parameter File\n`;
    text += `# Profile: ${profileName}\n`;
    text += `# Format: MiniDSP 2x4 HD / SHD Parametric Filter Set\n\n`;

    eqMatrix.forEach((item, index) => {
      const q = item.q || 1.414;
      text += `[PEQ_BAND_${index + 1}]\n`;
      text += `Type = PEAK\n`;
      text += `Frequency = ${item.freq}\n`;
      text += `Gain = ${item.gain.toFixed(2)}\n`;
      text += `Q = ${q.toFixed(2)}\n`;
      text += `Enabled = 1\n\n`;
    });

    triggerDownload(text, `${safeFileName}_minidsp_peq.txt`);
  };

  // 3. Peace Equalizer Preset (.txt)
  const exportPeacePreset = () => {
    let text = `[Peace Equalizer Preset]\n`;
    text += `Name=${profileName}\n`;
    text += `Description=Resonant Pulse Acoustic Correction\n`;
    text += `Preamp=0\n`;
    eqMatrix.forEach((item, i) => {
      text += `Filter${i + 1}=ON PK ${item.freq} ${item.gain.toFixed(1)} ${item.q || 1.41}\n`;
    });
    triggerDownload(text, `${safeFileName}_peace_preset.txt`);
  };

  // 4. FabFilter Pro-Q / JSON Preset (.json)
  const exportFabFilterJSON = () => {
    const json = {
      presetName: profileName,
      device: targetDevice,
      engineVersion: 'ResonantPulse_v2.5',
      bands: eqMatrix.map((item) => ({
        frequencyHz: item.freq,
        gainDb: item.gain,
        qFactor: item.q || 1.414,
        type: 'Peaking',
        enabled: true,
      })),
    };
    triggerDownload(JSON.stringify(json, null, 2), `${safeFileName}_fabfilter_preset.json`);
  };

  // 5. Convolution WAV Impulse Response Exporter (.wav 24-bit 48kHz)
  const exportWavImpulseResponse = async () => {
    setIsGeneratingWav(true);
    try {
      const sampleRate = 48000;
      const durationSeconds = 0.5; // 500ms FIR impulse
      const numFrames = sampleRate * durationSeconds;

      const offlineCtx = new OfflineAudioContext(1, numFrames, sampleRate);

      // Create unit impulse signal delta(t)
      const impulseBuffer = offlineCtx.createBuffer(1, numFrames, sampleRate);
      const channelData = impulseBuffer.getChannelData(0);
      channelData[0] = 1.0; // Delta peak at t=0

      const source = offlineCtx.createBufferSource();
      source.buffer = impulseBuffer;

      // Chain BiquadFilterNodes for each EQ band
      let lastNode: AudioNode = source;
      eqMatrix.forEach((band) => {
        const filter = offlineCtx.createBiquadFilter();
        filter.type = 'peaking';
        filter.frequency.setValueAtTime(band.freq, 0);
        filter.gain.setValueAtTime(band.gain, 0);
        filter.Q.setValueAtTime(band.q || 1.414, 0);

        lastNode.connect(filter);
        lastNode = filter;
      });

      lastNode.connect(offlineCtx.destination);
      source.start(0);

      const renderedBuffer = await offlineCtx.startRendering();
      const pcmData = renderedBuffer.getChannelData(0);

      // Encode PCM Float32Array to 16-bit / 24-bit WAV file format
      const wavBlob = createWavBlob(pcmData, sampleRate);
      triggerDownload(wavBlob, `${safeFileName}_inverse_IR.wav`);
    } catch (err: any) {
      console.error('WAV Impulse generation error:', err);
      alert('Failed to generate WAV impulse response: ' + err.message);
    } finally {
      setIsGeneratingWav(false);
    }
  };

  // Helper to construct binary WAV file blob
  const createWavBlob = (samples: Float32Array, sampleRate: number): Blob => {
    const buffer = new ArrayBuffer(44 + samples.length * 2);
    const view = new DataView(buffer);

    /* RIFF identifier */
    writeString(view, 0, 'RIFF');
    /* RIFF chunk length */
    view.setUint32(4, 36 + samples.length * 2, true);
    /* RIFF type */
    writeString(view, 8, 'WAVE');
    /* format chunk identifier */
    writeString(view, 12, 'fmt ');
    /* format chunk length */
    view.setUint32(16, 16, true);
    /* sample format (16-bit PCM) */
    view.setUint16(20, 1, true);
    /* channel count (1 = mono) */
    view.setUint16(22, 1, true);
    /* sample rate */
    view.setUint32(24, sampleRate, true);
    /* byte rate (sampleRate * 2) */
    view.setUint32(28, sampleRate * 2, true);
    /* block align */
    view.setUint16(32, 2, true);
    /* bits per sample */
    view.setUint16(34, 16, true);
    /* data chunk identifier */
    writeString(view, 36, 'data');
    /* data chunk length */
    view.setUint32(40, samples.length * 2, true);

    // Float32 to Int16 PCM conversion
    let offset = 44;
    for (let i = 0; i < samples.length; i++, offset += 2) {
      const s = Math.max(-1, Math.min(1, samples[i]));
      view.setInt16(offset, s < 0 ? s * 0x8000 : s * 0x7fff, true);
    }

    return new Blob([buffer], { type: 'audio/wav' });
  };

  const writeString = (view: DataView, offset: number, string: string) => {
    for (let i = 0; i < string.length; i++) {
      view.setUint8(offset + i, string.charCodeAt(i));
    }
  };

  return (
    <div className="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 shadow-xl space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between border-b border-slate-800 pb-4">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-cyan-500/10 text-cyan-400 border border-cyan-500/20">
            <Download className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              Hardware & DAW Calibration Exporter
              <span className="text-[10px] font-extrabold px-2 py-0.5 rounded-full bg-cyan-500/20 text-cyan-300 border border-cyan-500/40">
                PRO HARDWARE READY
              </span>
            </h3>
            <p className="text-[11px] text-slate-400">
              Export high-precision inverse filter sets to Equalizer APO, MiniDSP, Peace, FabFilter & Convolution Impulse (.wav)
            </p>
          </div>
        </div>
      </div>

      {downloadSuccess && (
        <div className="p-3 bg-emerald-500/10 border border-emerald-500/30 text-emerald-300 text-xs rounded-xl flex items-center gap-2 animate-fadeIn">
          <Check className="w-4 h-4 text-emerald-400 shrink-0" />
          <span>{downloadSuccess}</span>
        </div>
      )}

      {/* Export Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Equalizer APO (.txt) */}
        <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 flex flex-col justify-between hover:border-cyan-500/50 transition-all space-y-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-white flex items-center gap-1.5">
                <FileText className="w-4 h-4 text-cyan-400" />
                Equalizer APO
              </span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-900 text-slate-400 border border-slate-800">
                .txt
              </span>
            </div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              System-wide Windows driver correction. Directly paste or load into Equalizer APO Configuration Editor.
            </p>
          </div>

          <button
            onClick={exportEqualizerAPO}
            className="w-full flex items-center justify-center gap-2 px-3 py-2 bg-cyan-600 hover:bg-cyan-500 text-white text-xs font-bold rounded-xl shadow-md transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export Equalizer APO</span>
          </button>
        </div>

        {/* MiniDSP Hardware (.txt / .xml) */}
        <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 flex flex-col justify-between hover:border-indigo-500/50 transition-all space-y-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-white flex items-center gap-1.5">
                <Cpu className="w-4 h-4 text-indigo-400" />
                MiniDSP 2x4 HD / SHD
              </span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-900 text-slate-400 border border-slate-800">
                .txt / .xml
              </span>
            </div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Standalone hardware DSP calibration. Native import format for MiniDSP PEQ filter slots.
            </p>
          </div>

          <button
            onClick={exportMiniDSP}
            className="w-full flex items-center justify-center gap-2 px-3 py-2 bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold rounded-xl shadow-md transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export MiniDSP PEQ</span>
          </button>
        </div>

        {/* Convolution WAV Impulse Response (.wav) */}
        <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 flex flex-col justify-between hover:border-emerald-500/50 transition-all space-y-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-white flex items-center gap-1.5">
                <FileAudio className="w-4 h-4 text-emerald-400" />
                Convolution Impulse (.wav)
              </span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                48kHz 16-Bit WAV
              </span>
            </div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Calculates exact inverse Minimum-Phase FIR filter response. Load into Ableton, Space Designer, or FabFilter.
            </p>
          </div>

          <button
            onClick={exportWavImpulseResponse}
            disabled={isGeneratingWav}
            className="w-full flex items-center justify-center gap-2 px-3 py-2 bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold rounded-xl shadow-md transition-all cursor-pointer disabled:opacity-50"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>{isGeneratingWav ? 'Synthesizing IR...' : 'Export Inverse WAV IR'}</span>
          </button>
        </div>

        {/* Peace EQ Preset */}
        <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 flex flex-col justify-between hover:border-purple-500/50 transition-all space-y-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-white flex items-center gap-1.5">
                <Sliders className="w-4 h-4 text-purple-400" />
                Peace Equalizer
              </span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-900 text-slate-400 border border-slate-800">
                .txt
              </span>
            </div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Presets for Peace Equalizer GUI. Includes band gain, filter Q, and preamp gain.
            </p>
          </div>

          <button
            onClick={exportPeacePreset}
            className="w-full flex items-center justify-center gap-2 px-3 py-2 bg-purple-600 hover:bg-purple-500 text-white text-xs font-bold rounded-xl shadow-md transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export Peace Preset</span>
          </button>
        </div>

        {/* FabFilter Pro-Q / DAW JSON Preset */}
        <div className="bg-slate-950 border border-slate-800 rounded-xl p-4 flex flex-col justify-between hover:border-amber-500/50 transition-all space-y-4">
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold text-white flex items-center gap-1.5">
                <Layers className="w-4 h-4 text-amber-400" />
                DAW / FabFilter Pro-Q
              </span>
              <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-slate-900 text-slate-400 border border-slate-800">
                .json
              </span>
            </div>
            <p className="text-[11px] text-slate-400 leading-relaxed">
              Standard JSON parametric preset schema for software equalizers and DAW plugin loaders.
            </p>
          </div>

          <button
            onClick={exportFabFilterJSON}
            className="w-full flex items-center justify-center gap-2 px-3 py-2 bg-amber-600 hover:bg-amber-500 text-white text-xs font-bold rounded-xl shadow-md transition-all cursor-pointer"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export DAW JSON Preset</span>
          </button>
        </div>
      </div>
    </div>
  );
};
